---
openapi: 3.0.1
info:
  title: API Virtual Wallets
  version: v1
paths:
  "/api/v1/users":
    get:
      summary: list users
      responses:
        '200':
          description: successful
  "/api/v1/users/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show user
      responses:
        '200':
          description: successful
  "/api/v1/wallets/credit":
    post:
      summary: credit wallet
      responses:
        '200':
          description: successful
  "/api/v1/wallets/debit":
    post:
      summary: debit wallet
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3000/
